### ISSUE TITLE
Jupyterlab and tqdm_notebook

### ISSUE THREAD

**Issue by blahster** [tqdm/tqdm#394]
The following code errors out with, ```NameError: name 'IntProgress' is not defined```

```
import tqdm
tqdm.tqdm_notebook().pandas()
df.progress_apply(func, axis=1)
```
I imported ```ipywidgets.IntProgress``` with no luck.

Python=3.6
Jupyter=4.2.1 
Jupyter lab=0.18.1

**Comment by stonebig** [comment]
hi. on today jupyterlab-0.26.4 , ipywidgets-7.0.0b6, I get this on jupyterlab:
````
![tqdm](https://user-images.githubusercontent.com/4312421/29003473-9c557438-7ab7-11e7-9e3b-dc88c34a4d9e.PNG)
````

**Comment by Casyfill** [comment]
any update on that?

**Comment by lrq3000** [comment]
Seems like the imports changed again in the latest releases, I will need to have a look.

**Comment by jetou** [comment]
I'm having the same issue

**Comment by diimdeep** [comment]
Same error `NameError: name 'IntProgress' is not defined` with jupyter notebook
jupyter-client==5.2.3
jupyter-core==4.4.0
jupyterlab==0.31.12
jupyterlab-launcher==0.10.5

I fix this with
`/usr/local/bin/python3.6 -m pip install ipywidgets`
`jupyter nbextension enable --py --sys-prefix widgetsnbextension`

**Comment by OmegaNJU** [comment]
@diimdeep Thx，but still have problem, the progress bar can not present normally in jupyterlab(v = 0.32.0
Jupyter lab offers two way to run notebooks：

Using traditional jupyter notebook: browse server_ip:8888/tree
<img width="985" alt="2018-04-26 19 03 16" src="https://user-images.githubusercontent.com/5026687/39306415-ba6d2b8c-4992-11e8-9f78-979e489e8d85.png">

Using the jupyter lab style: browsing server_ip:8888/lab
<img width="1072" alt="2018-04-26 19 02 48" src="https://user-images.githubusercontent.com/5026687/39306429-c4fc18ce-4992-11e8-91a3-6098a1b3cdd4.png">

What's wrong with it?

**Comment by chengs** [comment]
I confirm this problem on my environment, but it is upstream, so IMHO, nothing can be done on tqdm.
Please try this, it worked on mine.
```
#usual installation 
pip install ipywidgets 
jupyter nbextension enable --py widgetsnbextension
#you are my saver!
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```



References:
https://github.com/jupyterlab/jupyterlab/issues/1548
https://github.com/kubeflow/kubeflow/pull/518/files

**Comment by flying-sheep** [comment]
that issue is now fixed, so we can look into this again!

**Comment by OmegaNJU** [comment]
@flying-sheep, seems like nested-loop still presents wrongly, so does my problem.

**Comment by dangpzanco** [comment]
I had the exact same problem as @OmegaNJU, I tried @chengs's solution and it solved it.
I am currently running the example without problems, my setup is the following:
Windows 10 (10.0.17134 Build 17134)
Python 3.6.5 (Anaconda)

```
jupyter                   1.0.0                    py36_4
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.4.0            py36h56e9d50_0
jupyterlab                0.32.1                   py36_0
jupyterlab_launcher       0.10.5                   py36_0
nodejs                    8.9.3                hd6b2f15_0
tqdm                      4.23.3                    <pip>
```


![image](https://user-images.githubusercontent.com/984981/40283314-8d26defc-5c52-11e8-9228-15ecc2d31bc3.png)

**Comment by fehiepsi** [comment]
I can confirm that all we need is to install the JupyterLab extension https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension

**Comment by martindurant** [comment]
The default text that appears in jupyterlab in the case that ipywidgets isn't installed but notebook output is requested, or ipywidgets is installed, but the labextension isn't, should be explicit about what's going on. [This](https://github.com/ContinuumIO/intake/blob/master/intake/gui/widgets.py#L130) is how I solved it for my other ipywidgets-based GUI elements. `Hbox(...)` just isn't very useful.

**Comment by outtoin** [comment]
@chengs Thanks a lot!!! You're my time saver 👍

**Comment by hellojinwoo** [comment]
The 3 command solution that @chengs posts totally work!! Thanks chengs!!

**Comment by Cstyler** [comment]
Don't forget to restart your jupyter after installing packages (mentioned here by @chengs).

**Comment by jnguyen1192** [comment]
> Same error `NameError: name 'IntProgress' is not defined` with jupyter notebook
> jupyter-client==5.2.3
> jupyter-core==4.4.0
> jupyterlab==0.31.12
> jupyterlab-launcher==0.10.5
> 
> I fix it with
> `/usr/local/bin/python3.6 -m pip install ipywidgets`
> `jupyter nbextension enable --py --sys-prefix widgetsnbextension`

Then restart kernel and refresh page (ctrl + F5)

**Comment by vfilimonov** [comment]
Let me follow-up on @stonebig 's example:
> ![tqdm](https://user-images.githubusercontent.com/4312421/29003485-def0d0c6-7ab7-11e7-8312-c808c15ada4a.PNG)

I notice that this situation also could happen sometimes if iterations are stopped via `KeyboardInterrupt` and/or reload of the jupyterlab page (I could not really come up with a reproducible sequence).

But once the output is broken, every new reload of the page makes it even worse, adding extra lines 
between progress outputs:
<img width="894" alt="Screenshot 2019-11-18 at 15 29 57 " src="https://user-images.githubusercontent.com/1324881/69060814-4e74ed00-0a18-11ea-8bac-87b732a3ff2b.png">

Does anyone know if/how could it be fixed without restarting the python kernel?

**Comment by casperdcl** [comment]
This is part of the infamous #548. I posted an example there (https://github.com/tqdm/tqdm/issues/548#issuecomment-457291936) where the bar is manually closed on interrupt:

```python
try:
    with tqdm(...) as t:
        for i in t:
            ...
except KeyboardInterrupt:
    t.close()
    raise
t.close()
```

**Comment by gingeard** [comment]
> The default text that appears in jupyterlab in the case that ipywidgets isn't installed but notebook output is requested, or ipywidgets is installed, but the labextension isn't, should be explicit about what's going on. [This](https://github.com/ContinuumIO/intake/blob/master/intake/gui/widgets.py#L130) is how I solved it for my other ipywidgets-based GUI elements. `Hbox(...)` just isn't very useful.

I've tried to install a clean environment with Python 3.8.1 and it's work. With Python 3.7.1, but with the same versions of packages, I was seeing only "HBox..." instead of widgets.

**Comment by mikful** [comment]
Within JupyterLab importing in the following manner and using normally is working for me, as per [this](https://github.com/PyTorchLightning/pytorch-lightning/issues/1112#issuecomment-599999278) answer.

`from tqdm import tqdm`

**Comment by AndrewWilliams3142** [comment]
I tried @chengs solution to this problem, but when I run `jupyter labextension install @jupyter-widgets/jupyterlab-manager` I get an error of the form:

```
Node v8.0.0

Yarn configuration loaded.
> /home/users/andreww/.nvm/versions/node/v8.0.0/bin/npm pack @jupyter-widgets/jupyterlab-manager
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Node v8.0.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node /home/users/andreww/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error marked@0.8.0: The engine "node" is incompatible with this module. Expected version ">= 8.16.2". Got "8.0.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

npm dependencies failed to install
Traceback (most recent call last):

  File "/home/users/andreww/miniconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/users/andreww/miniconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/home/users/andreww/miniconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "/home/users/andreww/miniconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 652, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

Exiting application: jupyter
```

I've tried upgrading my node using `nvm install 8.16.2`, `nvm use 8.16.2`, but that's just giving my the same error message but with `Expected version ">= 10". Got "8.16.20"`. Has anyone else had a similar issue?

**Comment by vfilimonov** [comment]
Just in case someone is still suffering from this bug: 

[progressbar2](https://github.com/WoLpH/python-progressbar) does not have this issue (breaking progress bar into multiple lines after `KeyboardInterrupt`).
After almost a year of cursing every time when I needed to interrupt execution, I've switched from back `tqdm` back to `progressbar2`. Which for me essentially amounted to replacing two lines in my wrapper function:
```python
def pbar(x):
    import tqdm
    return tqdm.tqdm(x)

res = [_ for _ in pbar(range(100))]
```
with 
```python
def pbar(x):
    import progressbar
    return progressbar.progressbar(x)

res = [_ for _ in pbar(range(100))]
```

P.S.. graphical `tqdm.notebook.tqdm` is cool! 👍👍👍 
However for me the downside is that the output together with **elapsed time**) is not saved with notebook and is lost when it is reopened. So in order to save timing I need to add extra `%time` ot `%%time`.

**Comment by casperdcl** [comment]
@vfilimonov you seem to be talking about a different issue (#548). Also it was fixed in `tqdm>4.44.1` :)

**Comment by vfilimonov** [comment]
@casperdcl wow, that's great news! 
I should have simply updated first! :-) And right, I confused the issue

**Comment by ValeryP** [comment]
What worked for me is:

1. Using

```
from tqdm.auto import tqdm, trange
```
![image](https://user-images.githubusercontent.com/3534020/81059214-52b29b00-8ed0-11ea-8151-92bf3ac65f2c.png)

instead of 

```
from tqdm import tqdm, trange
```

![image](https://user-images.githubusercontent.com/3534020/81059279-737af080-8ed0-11ea-8959-5d3fc82a29f6.png)

2. Running:

```
pip install ipywidgets 
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

3. Then restart the terminal sessions and Jupyter kernels

**Comment by tbenst** [comment]
Unfortunately, problem is back as of `python 3.8`, jupyter lab `0.35.4` and `@jupyter-widgets/jupyterlab-manager v0.38.1`. https://github.com/tqdm/tqdm/issues/394#issuecomment-384743637 does not solve.

**Comment by Dayro-9** [comment]
> What worked for me is:
> 
> 1. Using
> 
> ```
> from tqdm.auto import tqdm, trange
> ```
> 
> ![image](https://user-images.githubusercontent.com/3534020/81059214-52b29b00-8ed0-11ea-8151-92bf3ac65f2c.png)
> 
> instead of
> 
> ```
> from tqdm import tqdm, trange
> ```
> 
> ![image](https://user-images.githubusercontent.com/3534020/81059279-737af080-8ed0-11ea-8959-5d3fc82a29f6.png)
> 
> 1. Running:
> 
> ```
> pip install ipywidgets 
> jupyter nbextension enable --py widgetsnbextension
> jupyter labextension install @jupyter-widgets/jupyterlab-manager
> ```
> 
> 1. Then restart the terminal sessions and Jupyter kernels

Hello,thanks for your sharing, I run the following code in Google Colab:
```
from tqdm import tqdm
if is_in_notebook():
    from tqdm import tqdm_notebook as tqdm
```
The error content is:
` HBox(children=(FloatProgress(value=0.0, description='global step', max=20000.0, style=ProgressStyle(descriptio… main.py:140: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0 Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook` iters = tqdm(zip(source_train_dl, target_train_dl), desc=f'epoch {epoch_id} ', total=min(len(source_train_dl), len(target_train_dl)))`
So I modified the code according to your method to:
`from tqdm.auto import tqdm, trange`
The program can run normally, but the result is a bit strange, as follows:
<img width="465" alt="a794b2875dbc395fadd579ddd77e606" src="https://user-images.githubusercontent.com/59091691/96957917-8b9e0500-152e-11eb-90d5-dfde031bedc5.png">
Could you please help me to see how to solve this problem?Look forward to your reply!

**Comment by flying-sheep** [comment]
Colab doesn’t support `ipywidgets` I think, it has its own thing.

Therefore I guess tqdm is falling back to text output. And Colab also seems to not support the carriage return character `\r`, instead displaying a new line instead of an update.

**Comment by casperdcl** [comment]
@Dayro-9 your screenshot shows `!python` being run in a cell. That's as good as a terminal and not a notebook.

**Comment by hmaarrfk** [comment]
Running on colab (without `!python`) seems to work for me.
![image](https://user-images.githubusercontent.com/90008/97081388-04e13a80-15b7-11eb-8b47-7fa6ca263adb.png)

**Comment by Dayro-9** [comment]
> @Dayro-9 your screenshot shows `!python` being run in a cell. That's as good as a terminal and not a notebook.

Yes, I use colab as a command tool, because the` main.py` need to `import` other `.py`files , and I did not find a better way to run these code on colab. The ` import tqdm` is in `main.py`, and I met this error.So how can I solve it ?

**Comment by Dayro-9** [comment]
@flying-sheep Thank you, I think so, too

**Comment by Dayro-9** [comment]
@hmaarrfk Thanks, I tried to run on colab without `!python`,and it worked.

**Comment by casperdcl** [comment]
from https://github.com/tqdm/tqdm/issues/645#issuecomment-815148947 (@krassowski):

> Just heads up: it seems that you no longer need to install a separate JupyterLab extension (just ipywidgets which can be installed with `pip` or `conda`) for JupyterLab 3.0+. tada
> 
> You only need to upgrade ipywidgets. See: [ipywidgets.readthedocs.io/en/latest/user_install.html#installing-in-jupyterlab-3-0](https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-in-jupyterlab-3-0)

**Comment by flying-sheep** [comment]
Note that if the `jupyterlab` you use is installed in an environment separate from the one your kernel runs from, you probably need `ipywidgets` installed in *both*:

Jupyter env:

- `jupyter-core` (to provide `.../bin/jupyter`)
- `jupyterlab` (to provide `.../bin/jupyter-lab`)
- ***`ipywidgets`*** (to provide the jupyter lab extension displaying the widgets)

Kernel env:

- `ipykernel` (to install the kernel using `python -m ipykernel install ...`)
- ***`ipywidgets`*** (to create the widgets in the kernel process)

**Comment by h-joaomario** [comment]
I resolved by first installing nodejs

```sudo yum install -y nodejs```

then:

```jupyter labextension install @jupyter-widgets/jupyterlab-manager``` as described in jupyter labextension install @jupyter-widgets/jupyterlab-manager
