### ISSUE TITLE
No module called tqdm.autonotebook with pip installed version

### ISSUE THREAD

**Issue by song3134** [tqdm/tqdm#593]
I'm using the pip installed version of tqdm but get ''No module called tqdm.autonotebook''. The developed version is good so I believe the change of autonotobook module is not pushed on PyPI? In addition, i'm using the python 3.6 with ''_pydev_bundle.pydev_ipython_console_011.PyDevTerminalInteractiveShell'', the autonotebook provide me with ''tqdm'' rather than ''tqdm_notebook'', which still have the problem described in #443 . Thanks!

**Comment by casperdcl** [comment]
mentioned in https://github.com/tqdm/tqdm/commit/97a93932742db9e2c38672219a0aef8d1b3ad482#commitcomment-29855558, fixed by 1cf339325562ae863d33bd6131c92da43dd03435

**Comment by song3134** [comment]
Thanks for the quick reply! But still have the same two problems. 
1) pip install do not have this new module (autonotebook). (the developed version has)
2) PyCharm , python 3.6 with python ''_pydev_bundle.pydev_ipython_console_011.PyDevTerminalInteractiveShell'' do not have the nested progress bars (one iteration one new bar), it seems that both tqdm_notebook and tqdm can not solve this.

Thanks again!

**Comment by lukehsiao** [comment]
Can this be released as a patch (4.24.1)? We are also using pip to install `tqdm` and would like to use `autonotebook` rather than reimplementing the check ourselves, but cannot until this is released on PyPI.
